# Generated by Django 2.0 on 2020-05-27 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200526_1231'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-create_time'], 'verbose_name': '文章', 'verbose_name_plural': '文章'},
        ),
        migrations.AddField(
            model_name='post',
            name='view',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='浏览量'),
        ),
    ]
