# Generated by Django 2.2.3 on 2020-05-31 03:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_auto_20200527_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 31, 3, 21, 57, 206049, tzinfo=utc), verbose_name='创建时间'),
        ),
    ]
