# Generated by Django 2.2.3 on 2020-06-02 05:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0003_auto_20200531_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 2, 5, 22, 9, 654913, tzinfo=utc), verbose_name='创建时间'),
        ),
    ]
